services:
  localstack:
    image: localstack/localstack:4.12.0
    container_name: localstack-opentofu-workshop
    ports:
      - "4563-4599:4563-4599"
    environment:
      - SERVICES=s3,sts,s3control
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
