services:
  localstack:
    image: localstack/localstack:4.12.0
    container_name: localstack-opentofu-workshop
    ports:
      - "4563-4599:4563-4599"
    environment:
      - SERVICES=s3,sts,s3control
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./apps/todos/backend-py/app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./apps/todos/backend-py/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata